# Generated by Django 3.1.3 on 2020-12-03 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laboratorio',
            name='cnpj',
            field=models.CharField(max_length=14, verbose_name='CNPJ'),
        ),
    ]
