# Generated by Django 3.1.3 on 2020-12-03 23:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_auto_20201202_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='exame',
            name='CHCM',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='exame',
            name='HCM',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='exame',
            name='RDW',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='exame',
            name='VCM',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='exame',
            name='basofilos',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='exame',
            name='bastonetes',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='exame',
            name='data_criacao',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Criação'),
        ),
        migrations.AddField(
            model_name='exame',
            name='eosinofilos',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='exame',
            name='eritroblastos',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='exame',
            name='hemacias',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='exame',
            name='hematocrito',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='exame',
            name='leucocitos',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='exame',
            name='linfocitos',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='exame',
            name='linfocitos_atipicos',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='exame',
            name='metamielocitos',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='exame',
            name='mielocitos',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='exame',
            name='monocitos',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='exame',
            name='neutrofilos_totais',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='exame',
            name='plaquetas',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='exame',
            name='plasmocitos',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='exame',
            name='segmentados',
            field=models.FloatField(default=None),
        ),
        migrations.AlterField(
            model_name='exame',
            name='hemoglobina',
            field=models.FloatField(default=None),
        ),
    ]
