# Generated by Django 3.1.3 on 2020-12-04 00:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usuario', '0004_auto_20201203_2059'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exames',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Criação')),
                ('hemacias', models.FloatField(default=None)),
                ('hematocrito', models.FloatField(default=None)),
                ('hemoglobina', models.FloatField(default=None)),
                ('VCM', models.FloatField(default=None)),
                ('HCM', models.FloatField(default=None)),
                ('CHCM', models.FloatField(default=None)),
                ('RDW', models.FloatField(default=None)),
                ('eritroblastos', models.FloatField(default=None)),
                ('leucocitos', models.FloatField(default=None)),
                ('mielocitos', models.FloatField(default=None)),
                ('metamielocitos', models.FloatField(default=None)),
                ('bastonetes', models.FloatField(default=None)),
                ('segmentados', models.FloatField(default=None)),
                ('neutrofilos_totais', models.FloatField(default=None)),
                ('eosinofilos', models.FloatField(default=None)),
                ('basofilos', models.FloatField(default=None)),
                ('linfocitos', models.FloatField(default=None)),
                ('linfocitos_atipicos', models.FloatField(default=None)),
                ('monocitos', models.FloatField(default=None)),
                ('plasmocitos', models.FloatField(default=None)),
                ('plaquetas', models.FloatField(default=None)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
